# Generated by Django 4.1.2 on 2022-12-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
