# Generated by Django 4.1.2 on 2022-12-14 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='title',
        ),
    ]
