# Generated by Django 4.1.2 on 2022-12-15 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_service_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reviewee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewee', to='web.service'),
        ),
    ]
