# Generated by Django 4.1.2 on 2022-12-15 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_remove_review_reviewee_review_reviewed_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='description',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='review',
            name='reviewed_service',
        ),
    ]
