# Generated by Django 4.1.2 on 2022-12-16 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0013_review_reviewed_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='description',
            new_name='info',
        ),
        migrations.AddField(
            model_name='recommendation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='recommender', to=settings.AUTH_USER_MODEL),
        ),
    ]
