# Generated by Django 4.1.2 on 2022-12-16 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_rename_description_announcement_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='date_posted',
            field=models.DateField(default=datetime.datetime(2022, 12, 16, 13, 45, 36, 179350)),
        ),
    ]
