# Generated by Django 4.1.2 on 2022-12-16 11:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_announcement_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date_posted',
            field=models.DateField(default=datetime.datetime(2022, 12, 16, 11, 46, 45, 504646, tzinfo=datetime.timezone.utc)),
        ),
    ]
