# Generated by Django 4.1.2 on 2022-12-17 07:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_alter_announcement_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 12, 17, 7, 27, 37, 399792, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='service',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2022, 12, 17, 7, 27, 37, 398792, tzinfo=datetime.timezone.utc)),
        ),
    ]
