# Generated by Django 4.1.2 on 2022-12-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_review_date_service_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='date_added',
            field=models.DateField(),
        ),
    ]
