# Generated by Django 4.1.2 on 2022-12-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_recommendation_date_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='date_sent',
            field=models.DateField(),
        ),
    ]
